# Generated by Django 3.2.9 on 2021-12-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1200)),
                ('tag', models.CharField(choices=[('BUG', 'Bug'), ('IMPROV', 'Amélioration'), ('TASK', 'Tâche')], default='BUG', max_length=6)),
                ('status', models.CharField(choices=[('TD', 'A faire'), ('IP', 'En cours'), ('END', 'Terminé')], default='TD', max_length=3)),
                ('priority', models.CharField(choices=[('LP', 'Faible'), ('MP', 'Moyenne'), ('HP', 'Elevée')], default='LP', max_length=2)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('BE', 'Back-end'), ('FE', 'Front-end'), ('IS', 'iOS'), ('AD', 'Android')], default='BE', max_length=2)),
            ],
        ),
    ]
